# Generated by Django 5.2.7 on 2025-11-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publisghed_date',
            new_name='published_date',
        ),
    ]
